export const GET_MARS_CURIOSITY_PHOTOS = 'GET_MARS_CURIOSITY_PHOTOS';
export const GET_MARS_CURIOSITY_PHOTOS_SUCCESS =
  'GET_MARS_CURIOSITY_PHOTOS_SUCCESS';
export const GET_MARS_CURIOSITY_PHOTOS_FAILURE =
  'GET_MARS_CURIOSITY_PHOTOS_FAILURE';
